version: '3'
services :
  emasadb: 
    image: postgres
    hostname: postgresql
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_DB=emasa
      - POSTGRES_USER=
      - POSTGRES_PASSWORD= 
  pgadmin: 
    image: dpage/pgadmin4
    hostname: pgadmin
    ports:
      - 81:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=
    depends_on:
      - "emasadb"
